# Generated by Django 5.1.6 on 2025-02-21 07:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bullet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('_coo_x', models.IntegerField()),
                ('_coo_y', models.IntegerField()),
                ('_angle', models.IntegerField()),
                ('_speed', models.IntegerField(default=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('_coo_x', models.IntegerField()),
                ('_coo_y', models.IntegerField()),
                ('_speed', models.IntegerField(default=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('_score', models.IntegerField(default=0)),
                ('_life', models.IntegerField(default=3)),
            ],
        ),
    ]
