# Generated by Django 5.1.6 on 2025-02-24 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bullet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('_coo_x', models.IntegerField()),
                ('_coo_y', models.IntegerField()),
                ('_speed', models.IntegerField(default=100)),
                ('_angle', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('_coo_x', models.IntegerField()),
                ('_coo_y', models.IntegerField()),
                ('_speed', models.IntegerField(default=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('id', models.CharField(default='1', editable=False, max_length=10, primary_key=True, serialize=False)),
                ('_score', models.IntegerField(default=0)),
                ('_life', models.IntegerField(default=3)),
            ],
        ),
    ]
