# Generated by Django 5.1.6 on 2025-02-25 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shootgame', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boxenemy',
            old_name='created',
            new_name='_created',
        ),
        migrations.RenameField(
            model_name='bullet',
            old_name='created',
            new_name='_created',
        ),
    ]
