# Generated by Django 5.1.6 on 2025-02-26 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shootgame', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
