# Generated by Django 5.1.6 on 2025-02-25 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shootgame', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='_game_over',
        ),
        migrations.AlterField(
            model_name='bullet',
            name='number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
